import { Routes,Route,Link,useNavigate,useParams } from 'react-router-dom';
import { StoreProvider,useStore } from './context/StoreContext';
import { motion } from 'framer-motion';
const Navbar=()=>{const {cart}=useStore();return <nav className='sticky top-0 z-30 bg-cream/90 backdrop-blur p-4 flex justify-between'><Link to='/' className='text-2xl font-bold text-spiceRed'>Shimla Spice</Link><div className='space-x-4'><Link to='/dashboard'>Account</Link><Link to='/tracking'>Track Order</Link><span>🛒{cart.reduce((a,b)=>a+b.qty,0)}</span></div></nav>}
const Home=()=>{const {products,addToCart}=useStore();const nav=useNavigate();return <div><section className='p-10 bg-gradient-to-r from-cream to-orange-100 overflow-hidden'><h1 className='text-5xl text-spiceRed font-black'>Homemade Goodness in Every Jar</h1><p>From the hills of Himachal to your plate</p><div className='mt-4 space-x-3'><button onClick={()=>window.scrollTo({top:700,behavior:'smooth'})} className='bg-spiceRed text-white px-5 py-2 rounded-full'>Explore Pickles</button><button className='bg-mustard px-5 py-2 rounded-full'>Taste the Tradition</button></div><div className='float-spice text-5xl mt-4'>🌶️ 🥭 🫙</div></section>
<section className='grid md:grid-cols-3 gap-4 p-8'>{['Handmade, Not Factory Made','No preservatives','Small batch production'].map(t=><div key={t} className='rounded-2xl shadow p-4 bg-white'>{t}</div>)}</section>
<section className='p-8'><h2 className='text-3xl text-spiceRed mb-4'>Featured Products</h2><div className='grid md:grid-cols-3 gap-4'>{products.map(p=><motion.div whileHover={{y:-6}} key={p._id} className='bg-white rounded-2xl shadow p-4'><img src={p.image} className='h-44 w-full object-cover rounded-xl'/><h3 className='font-bold mt-2'>{p.name}</h3><p>{p.desc}</p><p className='text-spiceGreen font-bold'>₹{p.price}</p><p className='text-xs text-spiceRed'>Only {p.stock} jars left</p><div className='flex gap-2 mt-2'><button onClick={()=>addToCart(p)} className='bg-spiceGreen text-white px-3 py-2 rounded-full'>Add to Cart</button><button onClick={()=>nav(`/product/${p._id}`)} className='border px-3 py-2 rounded-full'>View</button></div></motion.div>)}</div></section>
<section className='p-8 bg-red-50'><h2 className='text-3xl text-spiceRed'>From Nanu's Kitchen</h2><p>A legacy from an army family table—slow roasted spices, sun-dried patience, and recipes passed whisper-to-whisper.</p></section>
<section className='p-8'><h2 className='text-2xl'>Loved by families</h2><div className='grid md:grid-cols-3 gap-3'>{['Tastes like my dadi made it.','Best with paratha!','Fresh and unapologetically spicy.'].map(r=><div key={r} className='bg-white p-4 rounded-xl shadow'>{r}</div>)}</div></section>
</div>}
const Product=()=>{const {id}=useParams();const {products,addToCart}=useStore();const p=products.find(x=>x._id===id);if(!p)return null;return <div className='p-8'><img src={p.image} className='w-full max-w-lg rounded-2xl'/><h1 className='text-4xl text-spiceRed'>{p.name}</h1><p>{p.desc}</p><p>Ingredients: mustard oil, native spices, Himalayan salt.</p><p>Spicy {'🌶️'.repeat(p.taste.spicy)} Tangy {'🍋'.repeat(p.taste.tangy)} Sweet {'🍯'.repeat(p.taste.sweet)}</p><button className='fixed md:static bottom-4 left-4 right-4 bg-spiceRed text-white p-3 rounded-full' onClick={()=>addToCart(p)}>Buy Now ₹{p.price}</button></div>}
const Dashboard=()=> <div className='p-8 space-y-4'><h1 className='text-3xl text-spiceRed'>My Dashboard</h1><div className='bg-white p-4 rounded-xl shadow'>Order history: #SS1024 Delivered</div><div className='bg-white p-4 rounded-xl shadow'>Saved address: Shimla Hills, HP</div><div className='bg-white p-4 rounded-xl shadow'>Wishlist: Mango Pickle</div></div>
const Tracking=()=> <div className='p-8'><h1 className='text-3xl text-spiceRed'>Order Tracking</h1><ol className='mt-4 space-y-2'>{['Ordered','Packed','Shipped','Delivered'].map((s,i)=><li key={s} className={`${i<3?'text-spiceGreen':'text-gray-400'}`}>● {s}</li>)}</ol></div>
export default function App(){return <StoreProvider><Navbar/><Routes><Route path='/' element={<Home/>}/><Route path='/product/:id' element={<Product/>}/><Route path='/dashboard' element={<Dashboard/>}/><Route path='/tracking' element={<Tracking/>}/></Routes></StoreProvider>}
